### ISSUE TITLE
Setup documentation not up-to-date with repo.

### ISSUE THREAD

**Issue by mkromann** [nullndr/remix-shopify#1]
Hi,

Thank you for taking the time to publish this.

I am entirely new to Shopify app development (but not Remix) and this has helped me grasp some concepts. However, I am struggling setting up this stack correctly. It seems that the setup documentation is not current, as the files referenced (eg. `app/routes/shopify/index`) does not exist in the repos current state. I found the other files to slot in the clientId token and the clientSecret token. But when trying to install the app on a dev store, I am getting a blank screen despite the url seeming correct (for the redirect/auth).

If I had the knowledge to fix it I would update the documentation but I have not been successful. I will attempt some more but if you get the time, it would be lovely if you could take a look at the current documentation for the setup.

Best regards,
Magnus

**Comment by nullndr** [comment]
Thank you @mkromann for the feedback, I will take a look right now.

**Comment by nullndr** [comment]
@mkromann I have updated both the project and the README file, please starts your project with the latest version of this stack and follow the points in the README file.

If your app works, close this issue.

Again, thanks for your feedback 👌🏼

**Comment by mkromann** [comment]
@nullndr Thank you. That got me a lot further.

I seem to have an issue with setting the cookie during the redirect in `initializeShopifyAuth()`. `validateShopifyRequest()` fails for me, as the cookie session storage cannot be retrieved thus I cannot get `stateFromSession`. This means `isValidState` fails and I get a `{ success: false }`.

I am not sure how to troubleshoot what happens during the redirect. I checked cookie storage in devtools, and it is empty.

**Comment by nullndr** [comment]
@mkromann this was an issue I had in an old project. You can avoid this commenting the following:

```ts
  if (!isVerifiedRequest || !isValidState) {
    return {
      success: false,
    };
  }
```

in the `remixShopify.server.ts` file.

However the source of the problem is the cross-site request between shopify and you with our session, I still don't know how to investigate this more further, please tell me if the solution works

**Comment by mkromann** [comment]
@nullndr I get a flash of the index page but then it redirects continuously.

```
GET /api/auth/callback?code=b63c028f0ad0cc301813db7033c89620&hmac=dc6276bb21750c74b136a494c8ccb07a4d4666cc2d39ff932426fee38daed59c&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ&shop=tryjani.myshopify.com&state=10eda1e4854d&timestamp=1680854436 302 - - 455.655 ms
GET /?shop=tryjani.myshopify.com&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ 302 - - 8.733 ms
GET /api/auth?shop=tryjani.myshopify.com&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ 302 - - 4.803 ms
GET /api/auth/callback?code=7516790f2894b6fedf35dbf0136d16aa&hmac=c43f7b108d2d7edd0bd8cd6b3706c964cf4de95eb2725e3a5a03f9f79972eb41&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ&shop=tryjani.myshopify.com&state=166e8942c108c&timestamp=1680854437 302 - - 369.831 ms
GET /?shop=tryjani.myshopify.com&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ 302 - - 5.724 ms
GET /api/auth?shop=tryjani.myshopify.com&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvdHJ5amFuaQ 302 - - 7.268 ms
```

Thank you for taking the time to assist.

**Comment by nullndr** [comment]
@mkromann this is strange, your session cookie should works fine, can you see if in the dev tools it is set or not?

**Comment by mkromann** [comment]
> @mkromann this is strange, your session cookie should works fine, can you see if in the dev tools it is set or not?

Doesn't seem to be set: 
<img width="896" alt="2023 04 07_10 42 59 • Google Chrome — tryjani · JANI · Shopify@2x" src="https://user-images.githubusercontent.com/1389467/230575730-4052d6ab-5dc7-448e-bca5-731a122f4bd9.png">

Is this what you mean?

**Comment by nullndr** [comment]
@mkromann 

> Is this what you mean?

Yes, you should see the following:

![image](https://user-images.githubusercontent.com/62137266/230584704-bb862e8e-4cb6-4248-8c37-9bbf8fe9765e.png)

Another fix could be to not block cross site scripting, since in some store I noticed that Shopify does not send the request to `/auth/callback`.

I think this is for some misconfiguration about the cookies, for example:

![image](https://user-images.githubusercontent.com/62137266/230586665-5eb51879-d850-4fb4-8d06-2916ff396918.png)


I use firefox, and when developing I use the following settings:

![image](https://user-images.githubusercontent.com/62137266/230585033-a6d149e9-504c-45ef-b374-abf04a8c2369.png)

I don't know if this can help you, give it a try and let me know

**Comment by mkromann** [comment]
Ok, that worked. 🙏 But I am wondering if this is a viable option going forward? Or is this only a development issue?

**Comment by mkromann** [comment]
Also, I can see that Shopify discourages cookie-based sessions going forward (https://shopify.dev/docs/apps/auth/oauth/session-tokens). This is not my forte but I imagine the limitations might also make it more difficult for a remix app (https://shopify.dev/docs/apps/auth/oauth/session-tokens)?

You most likely have a better understanding than me.

**Comment by nullndr** [comment]
@mkromann I'm currently building a huge app where I also have this issue. I still do not have any production environment so I am not able to see if it is only a development issue.

I will surely investigate it further, when I will have more news, I will also update this stack.

**Comment by mkromann** [comment]
> @mkromann I'm currently building a huge app where I also have this issue. I still do not have any production environment so I am not able to see if it is only a development issue.
> 
> I will surely investigate it further, when I will have more news, I will also update this stack.

Thanks. Appreciate your effort. I'll also let you know if I learn something :)

**Comment by nullndr** [comment]
> Also, I can see that Shopify discourages cookie-based sessions going forward (https://shopify.dev/docs/apps/auth/oauth/session-tokens). This is not my forte but I imagine the limitations might also make it more difficult for a remix app (https://shopify.dev/docs/apps/auth/oauth/session-tokens)?
> 
> You most likely have a better understanding than me.

The problem here is that Shopify does send you authenticated request when you navigate through the app with Shopify components like the [`<NavigationMenu>`](https://polaris.shopify.com/components/navigation/navigation).

But if you use a remix `<Link>` component then you won't have the request authenticated, so you must rely on other authenticated methods.

**Comment by nullndr** [comment]
@mkromann I will close this issue if you agree, if you have more questions please let me know.

Also please, if you find this stack helpful, give it a star ⭐
